Repository Nikhil636/Attendance-app, pull requests merged in 2023-02, with the labels that each got.

#12 The password reset feature added under JWOC.
  lib/Home.dart
  lib/Login.dart
  lib/main.dart
  lib/profile.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: Medium, JWOC

#16 #13 reverted PR resend
  .gitignore
  android/app/google-services.json
  assets/fonts/AnekDevanagari-Bold.ttf
  assets/fonts/AnekDevanagari-ExtraBold.ttf
  assets/fonts/AnekDevanagari-ExtraLight.ttf
  assets/fonts/AnekDevanagari-Light.ttf
  assets/fonts/AnekDevanagari-Medium.ttf
  assets/fonts/AnekDevanagari-Regular.ttf
  assets/fonts/AnekDevanagari-SemiBold.ttf
  assets/fonts/AnekDevanagari-Thin.ttf
  assets/fonts/KdamThmorPro-Regular.ttf
  assets/images/signup.png
  lib/calendar.dart
  lib/main.dart
  lib/profile.dart
  lib/shared/common_textfields.dart
  lib/shared/loader_dialog.dart
  lib/src/features/authentication/app/controllers/password_notifier.dart
  lib/src/features/authentication/app/controllers/signup_controller.dart
  lib/src/features/authentication/app/providers/auth_providers.dart
  lib/src/features/authentication/data/auth_repository.dart
  lib/src/features/authentication/domain/state/sign_up_state.dart
  lib/src/features/authentication/domain/state/sign_up_state.freezed.dart
  lib/src/features/authentication/presentation/login/Login.dart
  lib/src/features/authentication/presentation/signup/sign_up_screen.dart
  lib/src/features/home/Home.dart
  lib/src/providers/provider_observer.dart
  lib/src/utils/textfield_validators.dart
  lib/today.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: Hard, JWOC

#17 Solves Add proper linting rules for the application #14 under JWOC
  analysis_options.yaml
  assets/fonts/AnekDevanagari-Bold.ttf
  assets/fonts/AnekDevanagari-ExtraBold.ttf
  assets/fonts/AnekDevanagari-ExtraLight.ttf
  assets/fonts/AnekDevanagari-Light.ttf
  assets/fonts/AnekDevanagari-Medium.ttf
  assets/fonts/AnekDevanagari-Regular.ttf
  assets/fonts/AnekDevanagari-SemiBold.ttf
  assets/fonts/AnekDevanagari-Thin.ttf
  assets/fonts/KdamThmorPro-Regular.ttf
  build.yaml
  lib/main.dart
  lib/shared/common_textfields.dart
  lib/shared/loader_dialog.dart
  lib/src/app/constants/assets.gen.dart
  lib/src/app/theme/app_theme.dart
  lib/src/features/authentication/app/controllers/password_notifier.dart
  lib/src/features/authentication/app/controllers/signup_controller.dart
  lib/src/features/authentication/app/providers/auth_providers.dart
  lib/src/features/authentication/data/auth_repository.dart
  lib/src/features/authentication/domain/models/user_model.dart
  lib/src/features/authentication/domain/models/user_model.freezed.dart
  lib/src/features/authentication/domain/models/user_model.g.dart
  lib/src/features/authentication/presentation/login/login_screen.dart
  lib/src/features/authentication/presentation/signup/sign_up_screen.dart
  lib/src/features/home/Home.dart
  lib/src/features/home/calendar.dart
  lib/src/features/home/profile.dart
  lib/src/features/home/today.dart
  lib/src/features/home/usert.dart
  lib/today.dart
  lib/usert.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: Medium, JWOC

#21 SharedPreferences service using riverpod #18
  lib/main.dart
  lib/src/providers/shared_prefs_provider.dart
  pubspec.yaml
Labels: Easy, JWOC

#23 Solves QR code Scanner #2 issue under JWOC
  android/app/src/main/AndroidManifest.xml
  lib/src/features/qr_code_scanner/app/controller/qr_screen_controller.dart
  lib/src/features/qr_code_scanner/app/providers/qr_providers.dart
  lib/src/features/qr_code_scanner/domain/qr_state.dart
  lib/src/features/qr_code_scanner/domain/qr_state.freezed.dart
  lib/src/features/qr_code_scanner/presentation/qr_code_page.dart
  lib/src/utils/riverpod_extensions.dart
  pubspec.lock
  pubspec.yaml
Labels: Medium, JWOC

#25 Feature
  README.md
Labels: Easy, JWOC

#24 Solves Add Login with Phone number option issue #6 under JWOC
  lib/main.dart
  lib/src/features/authentication/app/controllers/login_controller.dart
  lib/src/features/authentication/app/controllers/signup_controller.dart
  lib/src/features/authentication/app/providers/auth_providers.dart
  lib/src/features/authentication/data/auth_methods.dart
  lib/src/features/authentication/data/auth_repository.dart
  lib/src/features/authentication/domain/models/user_model.dart
  lib/src/features/authentication/domain/models/user_model.freezed.dart
  lib/src/features/authentication/domain/models/user_model.g.dart
  lib/src/features/authentication/domain/state/login_state.dart
  lib/src/features/authentication/domain/state/login_state.freezed.dart
  lib/src/features/authentication/domain/state/sign_up_state.dart
  lib/src/features/authentication/presentation/login/login_screen.dart
  lib/src/features/home/Home.dart
  lib/src/features/home/profile.dart
  lib/src/providers/user_status_provider.dart
Labels: Medium, JWOC
